name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    name: Run Cypress Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # or your preferred version
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run --browser chrome --headless
          # Remove all unnecessary CI-specific configurations
          # No 'build', 'start', or 'wait-on' unless specifically needed